# Generated by Django 4.2.1 on 2023-05-25 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='personal_web',
            new_name='PersonalWeb',
        ),
    ]
